### PR TITLE
prevent initialization process from crashing due to deleted identities

### LINKED ISSUE #28: Write, Reply & Reply All dropdowns stop working if user account identity deleted
Thanks for making this plugin! I've appreciated it for years. I finally just upgraded thunderbird after years of hesitancy about loosing some old plugins and installed the tb78 version. I deleted some identities and Write, Reply & Reply All dropdowns stop working. I restarted TB and disabled then reenabled the plugin, but the workaround was uninstalling and reinstalling, which of course, deleted all my settings. Seems like bug that's easy to replicate. Thanks again!

### PR DESCRIPTION
**Pull request by MoralCode**
based on the information provided in #28 I did some experimenting and was able to isolate the issue to an `undefined`/empty value getting into the `identities` array that is used in `background.js` to set up the various menus and identities.

Notice the missing index 6 from this screenshot from the "Tools > Developer tools > debug addons > identity chooser > Console" menu (using a custom version of the addon that prints out the whole `identities` list:
Screenshot_20220902_101702

After applying this fix on my own thunderbird install and restarting, I was able to see the drop-down icon next to the "Write" icon which was the primary symptom that I noticed after having deleted an email account.

fixes #28 
this may also help fix other similar "its not working" issues  currently open, such as #35 and #18

### CODE REVIEW

**Comment by speedball2001** [comment]
Thank you for investigating the issue and providing a quick fix for it. While the

`if (identity !== undefined){ 
  ... 
}`

masks the issue I'd rather see the getIdentites() function in modules/identities.js 

https://github.com/speedball2001/identitychooser-mx/blob/a8e86b9588cb5c7f3215c49df6a57250bed87e54/modules/identities.js#L6 

modified to not include undefinied identies into the list. 

In the mean time, your change helps. Again, thank you.

**Comment by MoralCode** [comment]
> While the `if (identity !== undefined){ ... }`masks the issue I'd rather see the getIdentites() function in modules/identities.js modified to not include undefinied identies into the list.

You're right that would be a more proper way to accomplish this. After doing a little more diffing, it seems as though this issue is coming from `Options.getIdentitiesExtendedProps()` and how it stores the users order preference of identities in thunderbirds local storage.

Do you know of any event or other API that Identity Chooser could subscribe to so that it is notified when an identity is deleted so it can be subsequently removed from the list in localStorage when it is deleted?

Alternatively, i could possibly add some kind of "cleanup" function that checks the current list of identities against whats in localstorage and prunes any identities that were stored and have since been deleted since these dont seem to show up in the addon's settings menu.

Would you prefer one of these solutions over the other? or is there a different way you'd prefer to handle this?

**Comment by speedball2001** [comment]
> Do you know of any event or other API that Identity Chooser could subscribe to so that it is notified when an identity is deleted so it can be subsequently removed from the list in localStorage when it is deleted?

There is one, in fact. It wasn't avialable when I ported Identity Chooser to MailExtensions, but now we can listen to changes in identities and accounts with onDeleted and onUpdated functions:

https://webextension-api.thunderbird.net/en/102/identities.html
https://webextension-api.thunderbird.net/en/102/accounts.html

> Alternatively, i could possibly add some kind of "cleanup" function that checks the current list of identities against whats in localstorage and prunes any identities that were stored and have since been deleted since these dont seem to show up in the addon's settings menu.

Given that we have installations out there that already experienced this bug, I think that a cleanup function would make sense even if we listen to identity or account delete events.

**Comment by MoralCode** [comment]
> Given that we have installations out there that already experienced this bug, I think that a cleanup function would make sense even if we listen to identity or account delete events.

Not sure if this is the best place to continue the discussion now that the hotfix is merged.

in any case when going back into the code, I noticed the options UI seems to already have a mechanism for "cleaning up" identities (`options/options.js:identitiesChanged()`) when something changes. This suggests that changing a setting (such as reordering two identities and saving, then reverting the change if desired) may resolve the issue as well. If this behavior can somehow also be refactored into the backend so as to be independent of the UI when non-UI-related change events (such as those you linked above) come in, i think that would be the best "proper" solution to this issue

**Pull request merged**
